"""Add google_id to users

Revision ID: 0fcf3c6877a0
Revises: 2d148994b50c
Create Date: 2026-02-13 11:17:40.364725

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0fcf3c6877a0"
down_revision = "2d148994b50c"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_id", sa.String(length=256), nullable=True)
        )
        batch_op.create_unique_constraint("uq_user_google_id", ["google_id"])

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_google_id", type_="unique")
        batch_op.drop_column("google_id")

    # ### end Alembic commands ###


def upgrade_soundboards():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_soundboards():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
