"""Initial migration

Revision ID: 2d148994b50c
Revises:
Create Date: 2026-01-25 14:01:16.614108

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2d148994b50c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("role", sa.Enum("ADMIN", "USER", name="userrole"), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("avatar_path", sa.String(length=256), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=True),
        sa.Column("lockout_until", sa.String(length=32), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("social_x", sa.String(length=256), nullable=True),
        sa.Column("social_youtube", sa.String(length=256), nullable=True),
        sa.Column("social_website", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "favorites",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("soundboard_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "soundboard_id"),
    )
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("followed_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "followed_id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=256), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))

    op.drop_table("notifications")
    op.drop_table("follows")
    op.drop_table("favorites")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("admin_settings")
    # ### end Alembic commands ###


def upgrade_soundboards():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activities_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "playlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("playlists", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_playlists_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "soundboards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("theme_color", sa.String(length=7), nullable=True),
        sa.Column("theme_preset", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("soundboards", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_soundboards_is_public"), ["is_public"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_soundboards_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_soundboards_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_name"), ["name"], unique=True)

    op.create_table(
        "board_collaborators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("soundboard_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["soundboard_id"],
            ["soundboards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("board_collaborators", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_board_collaborators_soundboard_id"),
            ["soundboard_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_board_collaborators_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("soundboard_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["soundboard_id"],
            ["soundboards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_comments_soundboard_id"), ["soundboard_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_comments_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("soundboard_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["soundboard_id"],
            ["soundboards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ratings_soundboard_id"), ["soundboard_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ratings_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "soundboard_tags",
        sa.Column("soundboard_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["soundboard_id"],
            ["soundboards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("soundboard_id", "tag_id"),
    )
    op.create_table(
        "sounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("soundboard_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("file_path", sa.String(length=256), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("is_loop", sa.Boolean(), nullable=True),
        sa.Column("start_time", sa.Float(), nullable=True),
        sa.Column("end_time", sa.Float(), nullable=True),
        sa.Column("hotkey", sa.String(length=1), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("format", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["soundboard_id"],
            ["soundboards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sounds", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sounds_soundboard_id"), ["soundboard_id"], unique=False
        )

    op.create_table(
        "playlist_items",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("sound_id", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sound_id"],
            ["sounds.id"],
        ),
        sa.PrimaryKeyConstraint("playlist_id", "sound_id"),
    )
    # ### end Alembic commands ###


def downgrade_soundboards():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_items")
    with op.batch_alter_table("sounds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sounds_soundboard_id"))

    op.drop_table("sounds")
    op.drop_table("soundboard_tags")
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ratings_user_id"))
        batch_op.drop_index(batch_op.f("ix_ratings_soundboard_id"))

    op.drop_table("ratings")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_user_id"))
        batch_op.drop_index(batch_op.f("ix_comments_soundboard_id"))

    op.drop_table("comments")
    with op.batch_alter_table("board_collaborators", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_board_collaborators_user_id"))
        batch_op.drop_index(batch_op.f("ix_board_collaborators_soundboard_id"))

    op.drop_table("board_collaborators")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_name"))

    op.drop_table("tags")
    with op.batch_alter_table("soundboards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_soundboards_user_id"))
        batch_op.drop_index(batch_op.f("ix_soundboards_name"))
        batch_op.drop_index(batch_op.f("ix_soundboards_is_public"))

    op.drop_table("soundboards")
    with op.batch_alter_table("playlists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playlists_user_id"))

    op.drop_table("playlists")
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activities_user_id"))

    op.drop_table("activities")
    # ### end Alembic commands ###
